version: "3.1"
services:
  back_mrmac-app:
    build:
      context: ./back_mrmac
      dockerfile: Dockerfile
    container_name: back_mrmac_app_container
    # image: a7medabdo6/care_managment
    volumes:
      - ./back_mrmac/src:/back_mrmac_App/src:ro
    ports:
      - "7000:7000"
  react:
    build:
      context: ./front_mrmac
      dockerfile: Dockerfile
    container_name: React_front_mrmac_container
    volumes:
      - ./front_mrmac/src:/React_front_mrmac/src:ro
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
    restart: always

  # nginx:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.nginx
  #   # volumes:
  #   #     - ./Care_Frontend/build:/usr/share/nginx/html:ro
  #   ports:
  #     - 82:80
  #   restart: always
